/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      bond: {
        staker_addr?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      update_config: {
        burn_period?: number | null;
        community_fee?: Decimal | null;
        controller?: string | null;
        controller_fee?: Decimal | null;
        deposit_fee?: Decimal | null;
        max_unbond_count?: number | null;
        owner?: string | null;
        platform_fee?: Decimal | null;
        [k: string]: unknown;
      };
    }
  | {
      unbond: {
        amount: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      claim_unbond: {
        [k: string]: unknown;
      };
    }
  | {
      withdraw: {
        spec_amount?: Uint128 | null;
        [k: string]: unknown;
      };
    }
  | {
      register_hub: {
        hub_address: string;
        hub_type: HubType;
        token: string;
        [k: string]: unknown;
      };
    }
  | {
      burn: {
        amount: Uint128;
        min_profit?: Decimal | null;
        swap_operations: SwapOperation[];
        [k: string]: unknown;
      };
    }
  | {
      collect: {
        [k: string]: unknown;
      };
    }
  | {
      collect_hook: {
        prev_balance: Uint128;
        total_input_amount: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      collect_fee: {
        [k: string]: unknown;
      };
    }
  | {
      send_fee: {
        deposit_fee_ratio: Decimal;
        [k: string]: unknown;
      };
    };
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
export type HubType = "bluna" | "lunax" | "cluna" | "stluna";
/**
 * AssetInfo contract_addr is usually passed from the cw20 hook so we can trust the contract_addr is properly validated.
 */
export type AssetInfo =
  | {
      token: {
        contract_addr: string;
        [k: string]: unknown;
      };
    }
  | {
      native_token: {
        denom: string;
        [k: string]: unknown;
      };
    };

export interface SwapOperation {
  pair_address: string;
  to_asset_info: AssetInfo;
  [k: string]: unknown;
}
