/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      reward_info: {
        staker_addr: string;
        [k: string]: unknown;
      };
    }
  | {
      unbond: {
        staker_addr: string;
        [k: string]: unknown;
      };
    }
  | {
      state: {
        [k: string]: unknown;
      };
    }
  | {
      hubs: {
        [k: string]: unknown;
      };
    }
  | {
      burns: {
        [k: string]: unknown;
      };
    }
  | {
      simulate_collect: {
        [k: string]: unknown;
      };
    };
