npx json2ts -i ../contracts/contracts/spectrum_gov/schema/ -o ./src/app/services/api/gov
npx json2ts -i ../contracts/contracts/farms/spectrum_mirror_farm/schema/ -o ./src/app/services/api/mirror_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_spec_farm/schema/ -o ./src/app/services/api/spec_farm
npx json2ts -i ../contracts/contracts/spectrum_staker/schema/ -o ./src/app/services/api/staker
npx json2ts -i ../contracts/contracts/spectrum_token/schema/ -o ./src/app/services/api/token
npx json2ts -i ../contracts/contracts/spectrum_platform/schema/ -o ./src/app/services/api/platform
npx json2ts -i ../contracts/contracts/spectrum_wallet/schema/ -o ./src/app/services/api/wallet
npx json2ts -i ../contracts/contracts/farms/spectrum_anchor_farm/schema/ -o ./src/app/services/api/anchor_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_pylon_farm/schema/ -o ./src/app/services/api/pylon_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_terraworld_farm/schema/ -o ./src/app/services/api/terraworld_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_valkyrie_farm/schema/ -o ./src/app/services/api/valkyrie_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_orion_farm/schema/ -o ./src/app/services/api/orion_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_nexus_farm/schema/ -o ./src/app/services/api/nexus_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_nexus_nasset_psi_farm/schema/ -o ./src/app/services/api/nexus_nassets_psi_farm
npx json2ts -i ../contracts/contracts/farms/spectrum_pylon_liquid_farm/schema/ -o ./src/app/services/api/pylon_liquid_farm
