/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;

export interface InitMsg {
  init_hook?: InitHook | null;
  /**
   * Pair contract code ID, which is used to
   */
  pair_code_id: number;
  token_code_id: number;
  [k: string]: unknown;
}
export interface InitHook {
  contract_addr: HumanAddr;
  msg: Binary;
  [k: string]: unknown;
}
