/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigInfo {
  anchor_market: string;
  aust_token: string;
  owner: string;
  spectrum_gov: string;
  spectrum_token: string;
  terraswap_factory: string;
  [k: string]: unknown;
}
