/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;

export interface ConfigInfo {
  owner: HumanAddr;
  spectrum_gov: HumanAddr;
  spectrum_token: HumanAddr;
  [k: string]: unknown;
}
