/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PairType =
  | {
      xyk: {
        [k: string]: unknown;
      };
    }
  | {
      stable: {
        [k: string]: unknown;
      };
    }
  | {
      custom: string;
    };

export interface InstantiateMsg {
  /**
   * Contract address to send fees to
   */
  fee_address?: string | null;
  /**
   * Used for auto_stake from pools
   */
  generator_address: string;
  /**
   * Controls settings for factory, pools and tokenomics contracts
   */
  owner: string;
  /**
   * Pair contract code IDs which are allowed to create pairs
   */
  pair_configs: PairConfig[];
  token_code_id: number;
  [k: string]: unknown;
}
export interface PairConfig {
  code_id: number;
  is_disabled?: boolean | null;
  maker_fee_bps: number;
  pair_type: PairType;
  total_fee_bps: number;
  [k: string]: unknown;
}
