/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
export type AssetInfoBaseFor_String =
  | {
      cw20: {
        contract_addr: string;
        [k: string]: unknown;
      };
    }
  | {
      native: {
        denom: string;
        [k: string]: unknown;
      };
    };

export interface ConfigBaseFor_String {
  controller: string;
  gov: GovBaseFor_String;
  lending_bank: LendingBankBaseFor_String;
  leveraged_farm: LeveragedFarmBaseFor_String;
  max_debt_ratio: Decimal;
  max_diff: Decimal;
  max_utilization: Decimal;
  min_debt_ratio: Decimal;
  optimal_utilization: Decimal;
  oracle: OracleBaseFor_String;
  owner: string;
  pair: PairBaseFor_String;
  spec_token: string;
  [k: string]: unknown;
}
export interface GovBaseFor_String {
  contract_addr: string;
  credits: StakeCredit[];
  [k: string]: unknown;
}
export interface StakeCredit {
  credit: Decimal;
  days: number;
  [k: string]: unknown;
}
export interface LendingBankBaseFor_String {
  contract_addr: string;
  [k: string]: unknown;
}
export interface LeveragedFarmBaseFor_String {
  borrow_asset_info: AssetInfoBaseFor_String;
  contract_addr: string;
  is_provide_a: boolean;
  provide_asset_info: AssetInfoBaseFor_String;
  [k: string]: unknown;
}
export interface OracleBaseFor_String {
  contract_addr: string;
  [k: string]: unknown;
}
export interface PairBaseFor_String {
  /**
   * Address of the Astroport contract_addr contract
   */
  contract_addr: string;
  /**
   * Address of the Astroport LP token
   */
  share_token: string;
  [k: string]: unknown;
}
