/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      receive: Cw20ReceiveMsg;
    }
  | {
      bond_native: {
        belief_price: Decimal;
        max_spread: Decimal;
        [k: string]: unknown;
      };
    }
  | {
      unbond: {
        amount?: Uint128 | null;
        belief_price: Decimal;
        max_spread: Decimal;
        [k: string]: unknown;
      };
    }
  | {
      withdraw: {
        spec_amount?: Uint128 | null;
        [k: string]: unknown;
      };
    }
  | {
      adjust_position: {
        belief_price: Decimal;
        max_spread: Decimal;
        [k: string]: unknown;
      };
    }
  | {
      update_config: {
        controller?: string | null;
        credits?: StakeCredit[] | null;
        owner?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      update_position_parameters: {
        max_debt_ratio?: Decimal | null;
        max_diff?: Decimal | null;
        max_utilization?: Decimal | null;
        min_debt_ratio?: Decimal | null;
        optimal_utilization?: Decimal | null;
        [k: string]: unknown;
      };
    }
  | {
      callback: CallbackMsg;
    };
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
export type CallbackMsg =
  | {
      bond_hook: {
        prev_bond_amount: Uint128;
        prev_debt_amount: Uint128;
        staker_addr: Addr;
        [k: string]: unknown;
      };
    }
  | {
      unbond_hook: {
        belief_price: Decimal;
        max_spread: Decimal;
        prev_borrow_amount: Uint128;
        prev_provide_amount: Uint128;
        staker_addr: Addr;
        [k: string]: unknown;
      };
    };
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;

/**
 * Cw20ReceiveMsg should be de/serialized under `Receive()` variant in a ExecuteMsg
 */
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface StakeCredit {
  credit: Decimal;
  days: number;
  [k: string]: unknown;
}
