/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cw20HookMsg =
  | {
      poll_start: {
        description: string;
        execute_msgs: PollExecuteMsg[];
        link?: string | null;
        title: string;
        [k: string]: unknown;
      };
    }
  | {
      stake_tokens: {
        days?: number | null;
        staker_addr?: string | null;
        [k: string]: unknown;
      };
    };
export type PollExecuteMsg = {
  execute: {
    contract: string;
    msg: string;
    [k: string]: unknown;
  };
};
