/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cw20HookMsg =
  | {
      poll_start: {
        description: string;
        execute_msgs: ExecuteMsg[];
        link?: string | null;
        title: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      stake_tokens: {
        staker_addr?: HumanAddr | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type ExecuteMsg = {
  execute: {
    contract: HumanAddr;
    msg: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type HumanAddr = string;
