/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleMsg =
  | {
      mint: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      poll_end: {
        poll_id: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      poll_execute: {
        poll_id: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      poll_expire: {
        poll_id: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      poll_vote: {
        amount: Uint128;
        poll_id: number;
        vote: VoteOption;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      receive: Cw20ReceiveMsg;
      [k: string]: unknown;
    }
  | {
      update_config: {
        effective_delay?: number | null;
        expiration_period?: number | null;
        mint_end?: number | null;
        mint_per_block?: Uint128 | null;
        mint_start?: number | null;
        owner?: HumanAddr | null;
        proposal_deposit?: Uint128 | null;
        quorum?: Decimal | null;
        spec_token?: HumanAddr | null;
        threshold?: Decimal | null;
        voting_period?: number | null;
        warchest_address?: HumanAddr | null;
        warchest_ratio?: Decimal | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      upsert_vault: {
        vault_address: HumanAddr;
        weight: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      withdraw: {
        amount?: Uint128 | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type Uint128 = string;
export type VoteOption = "yes" | "no";
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;
export type HumanAddr = string;
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;

/**
 * Cw20ReceiveMsg should be de/serialized under `Receive()` variant in a HandleMsg
 */
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg?: Binary | null;
  sender: HumanAddr;
  [k: string]: unknown;
}
