/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;
export type Uint128 = string;
export type ExecuteMsg = {
  execute: {
    contract: HumanAddr;
    msg: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type PollStatus = "in_progress" | "passed" | "rejected" | "executed" | "expired";

export interface PollsResponse {
  polls: PollInfo[];
  [k: string]: unknown;
}
export interface PollInfo {
  creator: HumanAddr;
  deposit_amount: Uint128;
  description: string;
  end_height: number;
  execute_msgs: ExecuteMsg[];
  id: number;
  link?: string | null;
  no_votes: Uint128;
  status: PollStatus;
  title: string;
  total_balance_at_end_poll?: Uint128 | null;
  yes_votes: Uint128;
  [k: string]: unknown;
}
