/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Uint128 = string;

export interface StateInfo {
  last_mint: number;
  poll_count: number;
  poll_deposit: Uint128;
  total_share: Uint128;
  total_staked: Uint128;
  total_weight: number;
  [k: string]: unknown;
}
