/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VaultsResponse {
  vaults: VaultInfo[];
  [k: string]: unknown;
}
export interface VaultInfo {
  address: string;
  weight: number;
  [k: string]: unknown;
}
