/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AssetInfoBaseFor_String =
  | {
      cw20: {
        contract_addr: string;
        [k: string]: unknown;
      };
    }
  | {
      native: {
        denom: string;
        [k: string]: unknown;
      };
    };

export interface ConfigBaseFor_String {
  /**
   * Info of the primary asset
   */
  asset_info_a: AssetInfoBaseFor_String;
  /**
   * Info of the secondary asset
   */
  asset_info_b: AssetInfoBaseFor_String;
  /**
   * Bank for asset A
   */
  bank_a: HomoraBankBaseFor_String;
  /**
   * Bank for asset B
   */
  bank_b: HomoraBankBaseFor_String;
  /**
   * Mars oracle contract
   */
  oracle: OracleBaseFor_String;
  /**
   * Astroport pair of primary/secondary assets
   */
  pair: PairBaseFor_String;
  /**
   * Staking contract where share tokens can be bonded to earn rewards
   */
  staking: StakingBaseFor_String;
  [k: string]: unknown;
}
export interface HomoraBankBaseFor_String {
  contract_addr: string;
  [k: string]: unknown;
}
export interface OracleBaseFor_String {
  contract_addr: string;
  [k: string]: unknown;
}
export interface PairBaseFor_String {
  /**
   * Address of the Astroport contract_addr contract
   */
  contract_addr: string;
  /**
   * Address of the Astroport LP token
   */
  share_token: string;
  [k: string]: unknown;
}
export interface StakingBaseFor_String {
  /**
   * Address of ANC, MIR, or mAsset token; refer to Mirror contract for definition
   */
  asset_token: string;
  /**
   * Address of the staking contract
   */
  contract_addr: string;
  /**
   * Address of Gov
   */
  gov: string;
  /**
   * Address of SPEC
   */
  reward_token: string;
  [k: string]: unknown;
}
