/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      state: {
        [k: string]: unknown;
      };
    }
  | {
      position: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
        [k: string]: unknown;
      };
    }
  | {
      positions: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      snapshot: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
        [k: string]: unknown;
      };
    }
  | {
      metadata: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      snapshots: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    };
