/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AnyoneMsg =
  | {
      register_token: {
        psi_token: string;
        [k: string]: unknown;
      };
    }
  | {
      cast_vote: {
        amount: Uint128;
        poll_id: number;
        vote: VoteOption;
        [k: string]: unknown;
      };
    }
  | {
      withdraw_voting_tokens: {
        amount?: Uint128 | null;
        [k: string]: unknown;
      };
    }
  | {
      end_poll: {
        poll_id: number;
        [k: string]: unknown;
      };
    }
  | {
      execute_poll: {
        poll_id: number;
        [k: string]: unknown;
      };
    }
  | {
      snapshot_poll: {
        poll_id: number;
        [k: string]: unknown;
      };
    };
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
export type VoteOption = "yes" | "no";
