/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cw20HookMsg =
  | {
      stake_voting_tokens: {
        [k: string]: unknown;
      };
    }
  | {
      create_poll: {
        description: string;
        execute_msgs?: PollExecuteMsg[] | null;
        link?: string | null;
        migrate_msgs?: PollMigrateMsg[] | null;
        title: string;
        [k: string]: unknown;
      };
    };
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;

export interface PollExecuteMsg {
  contract: string;
  msg: Binary;
  order: number;
  [k: string]: unknown;
}
export interface PollMigrateMsg {
  contract: string;
  msg: Binary;
  new_code_id: number;
  order: number;
  [k: string]: unknown;
}
