/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigResponse {
  base_denom: string;
  mint_contract: string;
  mirror_token: string;
  oracle_contract: string;
  owner: string;
  premium_min_update_interval: number;
  short_reward_contract: string;
  terraswap_factory: string;
  [k: string]: unknown;
}
