/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cw20HookMsg =
  | {
      bond: {
        asset_token: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      deposit_reward: {
        rewards: [HumanAddr, Uint128][];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type Uint128 = string;
