/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      pool_info: {
        asset_token: string;
        [k: string]: unknown;
      };
    }
  | {
      reward_info: {
        asset_token?: string | null;
        staker_addr: string;
        [k: string]: unknown;
      };
    };
