/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;
export type Uint128 = string;

export interface RewardInfoResponse {
  reward_infos: RewardInfoResponseItem[];
  staker_addr: HumanAddr;
  [k: string]: unknown;
}
export interface RewardInfoResponseItem {
  asset_token: HumanAddr;
  bond_amount: Uint128;
  is_short: boolean;
  pending_reward: Uint128;
  [k: string]: unknown;
}
