/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      poll_end: {
        poll_id: number;
        [k: string]: unknown;
      };
    }
  | {
      poll_execute: {
        poll_id: number;
        [k: string]: unknown;
      };
    }
  | {
      poll_expire: {
        poll_id: number;
        [k: string]: unknown;
      };
    }
  | {
      poll_start: {
        description: string;
        execute_msgs: PollExecuteMsg[];
        link?: string | null;
        title: string;
        [k: string]: unknown;
      };
    }
  | {
      poll_vote: {
        poll_id: number;
        vote: VoteOption;
        [k: string]: unknown;
      };
    }
  | {
      update_config: {
        effective_delay?: number | null;
        expiration_period?: number | null;
        owner?: string | null;
        quorum?: Decimal | null;
        threshold?: Decimal | null;
        voting_period?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      upsert_board: {
        address: string;
        weight: number;
        [k: string]: unknown;
      };
    };
export type PollExecuteMsg = {
  execute: {
    contract: string;
    msg: string;
    [k: string]: unknown;
  };
};
export type VoteOption = "yes" | "no";
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
