/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VoteOption = "yes" | "no";

export interface VotersResponse {
  voters: [string, VoterInfo][];
  [k: string]: unknown;
}
export interface VoterInfo {
  balance: number;
  vote: VoteOption;
  [k: string]: unknown;
}
