/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstantiateMsg {
  reward_token: string;
  reward_token_decimals: number;
  staking_token: string;
  staking_token_decimals: number;
  [k: string]: unknown;
}
