/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigInfo {
  lock_end: number;
  lock_start: number;
  owner: string;
  spectrum_gov: string;
  spectrum_token: string;
  [k: string]: unknown;
}
