/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Uint128 = string;
export type HumanAddr = string;

export interface MinterResponse {
  /**
   * cap is how many more tokens can be issued by the minter
   */
  cap?: Uint128 | null;
  minter: HumanAddr;
  [k: string]: unknown;
}
