/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal256(1_000_000_000_000_000_000) == 1.0 The greatest possible value that can be represented is 115792089237316195423570985008687907853269984665640564039457.584007913129639935 (which is (2^128 - 1) / 10^18)
 */
export type Decimal256 = string;

export interface InstantiateMsg {
  /**
   * Anchor token distribution speed
   */
  anc_emission_rate: Decimal256;
  /**
   * Anchor token code ID used to instantiate
   */
  aterra_code_id: number;
  /**
   * Maximum allowed borrow rate over deposited stable balance
   */
  max_borrow_factor: Decimal256;
  /**
   * Owner address for config update
   */
  owner_addr: string;
  /**
   * stable coin denom used to borrow & repay
   */
  stable_denom: string;
  [k: string]: unknown;
}
